# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd88d8fa04d61e6f6dbc1fa15028d6d5309c011510fe265a483410f8c04a012dc43c432f96d4c99ba72b8ad941f134a14c4211bc5b493f8408cbaa84072e50db

test:
  secret_key_base: e3fd7e42271d3e33db822c05f12ae73c63b810dd117ad3c4812667d6335ae716dbba5d2b234cd408fda0520f0a778ecc8ceca9d1bb618187d4840383d83e6e35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
